name       : kotlin-native
version    : 1.3.50
release    : 1
source     :
    - https://github.com/JetBrains/kotlin-native/archive/v1.3.50.tar.gz : 2c20e3f79f223beba2c37bca761e8507e946ed4e4c5893ef5586dc5d7844357c
license    : Apache-2.0
component  : programming
summary    : Standalone compiler toolchain for native Kotlin applications and libraries
description: |
    Kotlin/Native is a LLVM backend for the Kotlin compiler, runtime implementation and native code generation facility using LLVM toolchain.
    
    Kotlin/Native is primarily designed to allow compilation for platforms where virtual machines are not desirable or possible (such as iOS, embedded targets), or where developer is willing to produce reasonably-sized self-contained program without need to ship an additional execution runtime.
networking : true
environment: |
    # prevents Gradle wrapper from failing to extract to ~/.gradle
    export GRADLE_USER_HOME=$PWD/.gradle
    # prevents Java from failing to create ~/.java
    export HOME=$PWD/.home
    # prevents Konan from failing to create ~/.konan
    export KONAN_DATA_DIR=$PWD/.konan
builddeps  :
    - openjdk-8
rundeps    : 
    - openjdk-8
setup      : |
    ./gradlew dependencies:update
build      : |
    ./gradlew bundle
check      : |
    ./gradlew backend.native:tests:run
install    : |
    mkdir -p $installdir/usr/share/kotlin-native
    cp -r dist/* $installdir/usr/share/kotlin-native
    chmod -R 00644 $installdir/usr/share/kotlin-native 
    chmod -R +x $installdir/usr/share/kotlin-native/bin

    mkdir -p $installdir/usr/bin
    cd $installdir/usr/share/kotlin-native/bin
    
    for FILE in *; do
        ln -s /usr/share/kotlin-native/bin/$FILE $installdir/usr/bin/
    done
