name       : kotlin-native
version    : 1.4.21
release    : 10
source     :
    - https://github.com/JetBrains/kotlin-native/archive/v1.4.21.tar.gz : ebd56cbce6f069c88372eb3ff6bf69b6e638d0c6607800fea2e13579b8b9872b
    - https://download.jetbrains.com/kotlin/native/clang-llvm-8.0.0-linux-x86-64.tar.gz : a9ebf55170bdbe5e089dbf884e0bc52065b5b7bc52e9354415e25a36e10e56c5
    - https://download.jetbrains.com/kotlin/native/target-gcc-toolchain-2-linux-mips.tar.gz : b1703b2f0e1fc9e5620330f1d43c00b85ae65289796a51b827db81335207ff01
    - https://download.jetbrains.com/kotlin/native/target-gcc-toolchain-3-linux-x86-64.tar.gz : ca25fc933fe45deb142f2672d3773227a65e652ebeb7bc6cc8425f747c5f8912
    - https://download.jetbrains.com/kotlin/native/target-toolchain-2-linux-android_ndk.tar.gz : c53c127a26eec3e471a2f8fcb88484b8b22832aafd9115205b33beb84255dd10
    - https://download.jetbrains.com/kotlin/native/target-sysroot-1-android_ndk.tar.gz : 7dafa395f57c72dd728ad032516903fd711c1f2f1eaeaf997065431eec65ff36
    - https://download.jetbrains.com/kotlin/native/target-sysroot-1-linux-glibc-arm64.tar.gz : 09983b77875e376b5ae05eeff470d371e8c2832f492b3dbf92cbe08ef240d00b
    - https://download.jetbrains.com/kotlin/native/target-sysroot-2-mipsel.tar.gz : 8ecdc6382db848ce55938c516bbea0ebd9fc20e7f6df478e9af41d467b6fa683
    - https://download.jetbrains.com/kotlin/native/target-sysroot-2-raspberrypi.tar.gz : b0c7db1e5408d336baefa1af1f766e977ce05cc256bd24fb36be29d9816be71e
license    : Apache-2.0
component  : programming
homepage   : https://kotlinlang.org/docs/reference/native-overview.html
summary    : Standalone compiler toolchain for native Kotlin applications and libraries
description: |
    Kotlin/Native is a LLVM backend for the Kotlin compiler, runtime implementation and native code generation facility using LLVM toolchain.

    Kotlin/Native is primarily designed to allow compilation for platforms where virtual machines are not desirable or possible (such as embedded targets), or where a developer wants to produce a reasonably-sized self-contained program without the need to ship an additional execution runtime.
networking : true
builddeps  :
    - gradle
rundeps    :
    - openjdk-11
environment: |
    export KONAN_DATA_DIR="$workdir/.konan_home"
setup      : |
    mkdir -p $KONAN_DATA_DIR/dependencies/
    for FILE in $(find $sources -type f -not -name "v%version%*.tar.gz"); do
        tar -xzf $FILE -C $KONAN_DATA_DIR/dependencies/
        echo $(basename -s .tar.gz $FILE) >> $KONAN_DATA_DIR/dependencies/.extracted
    done
build      : |
    export GRADLE_USER_HOME="$workdir/.gradle_home"
    export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$workdir/.java_prefs/.userPrefs -Djava.util.prefs.systemRoot=$workdir/.java_prefs"

    gradle :dependencies:update bundle --no-daemon --stacktrace -Ptest.disable_update=true
install    : |
    install -Dm 00755 dist/bin/* -t $installdir/usr/share/kotlin-native/bin/
    cp -r dist/{klib,konan,tools} $installdir/usr/share/kotlin-native/

    sed -i "2r $pkgfiles/java-shim.txt" $installdir/usr/share/kotlin-native/bin/run_konan

    install -dm 00755 $installdir/usr/bin/
    for FILE in $(basename -a $installdir/usr/share/kotlin-native/bin/*); do
        ln -s /usr/share/kotlin-native/bin/$FILE $installdir/usr/bin/$FILE
    done

    find $installdir/usr/share/kotlin-native/ -type d -empty -delete
